# Git related aliases
alias git='hub'

alias gcl='git clone'
alias ga='git add'
alias gap='git add -p'
alias gall='git add -A'
alias gf='git fetch --all --prune'
alias g='hub'
alias gst='git status'
alias gs='git status'
alias gpr='git pull rebase'
alias gp='git push'
alias gpo='git push origin'
alias gpom='git push origin master'
alias gpm='git push origin master'
alias gpf='git push -f'
alias gcm='git commit -v -m'
alias gca='git commit --amend'
alias gb='git branch'
alias gco='git checkout'
alias gcom='git checkout master'
alias gcb='git checkout -b'
alias gcob='git checkout -b'
