# Phoenix aliases
alias i='iex'
alias ips='iex -S mix phoenix.server'
alias ism='iex -S mix'
alias m='mix'
alias mdg='mix deps.get'
alias mdu='mix deps.update'
alias mec='mix ecto.create'
alias mecm='mix do ecto.create, ecto.migrate'
alias med='mix ecto.drop'
alias mem='mix ecto.migrate'
alias megm='mix ecto.gen.migration'
alias merb='mix ecto.rollback'
alias mers='mix ecto.reset'
alias mn='mix new'
alias mpn='mix phoenix.new'
alias mt='mix test'
alias mtw='mix test.watch'
